#pragma once
// 自动生成：Theme 逐字段比较（避免 memcmp 的 padding 陷阱）。由 theme.h 生成，勿手改。
#include "ui/theme.h"

namespace fr {
inline const char* theme_first_diff(const Theme& a, const Theme& b) {
  auto C = [](NVGcolor x, NVGcolor y) { return x.r == y.r && x.g == y.g && x.b == y.b && x.a == y.a; };
  if (!C(a.topBarBg, b.topBarBg)) return "topBarBg";
  if (!C(a.barBg, b.barBg)) return "barBg";
  if (!C(a.barBorderTopBar, b.barBorderTopBar)) return "barBorderTopBar";
  if (!C(a.barBorderBottomBar, b.barBorderBottomBar)) return "barBorderBottomBar";
  if (!C(a.titleText, b.titleText)) return "titleText";
  if (!C(a.subText, b.subText)) return "subText";
  if (!C(a.mutedText, b.mutedText)) return "mutedText";
  if (!C(a.badgeBg, b.badgeBg)) return "badgeBg";
  if (!C(a.badgeText, b.badgeText)) return "badgeText";
  if (!C(a.icon, b.icon)) return "icon";
  if (!C(a.iconDim, b.iconDim)) return "iconDim";
  if (!C(a.iconDisabled, b.iconDisabled)) return "iconDisabled";
  if (!C(a.winIcon, b.winIcon)) return "winIcon";
  if (!C(a.winHoverBg, b.winHoverBg)) return "winHoverBg";
  if (!C(a.winPressBg, b.winPressBg)) return "winPressBg";
  if (!C(a.winCloseHoverBg, b.winCloseHoverBg)) return "winCloseHoverBg";
  if (!C(a.winClosePressBg, b.winClosePressBg)) return "winClosePressBg";
  if (!C(a.winCloseHoverIcon, b.winCloseHoverIcon)) return "winCloseHoverIcon";
  if (!C(a.btnHoverBg, b.btnHoverBg)) return "btnHoverBg";
  if (!C(a.btnPressBg, b.btnPressBg)) return "btnPressBg";
  if (!C(a.muteIcon, b.muteIcon)) return "muteIcon";
  if (!C(a.muteTrack, b.muteTrack)) return "muteTrack";
  if (!C(a.muteKnob, b.muteKnob)) return "muteKnob";
  if (!C(a.track, b.track)) return "track";
  if (!C(a.buffer, b.buffer)) return "buffer";
  if (!C(a.played, b.played)) return "played";
  if (!C(a.knob, b.knob)) return "knob";
  if (!C(a.knobHaloDrag, b.knobHaloDrag)) return "knobHaloDrag";
  if (!C(a.chapterTick, b.chapterTick)) return "chapterTick";
  if (!C(a.playButtonBg, b.playButtonBg)) return "playButtonBg";
  if (!C(a.playButtonBorder, b.playButtonBorder)) return "playButtonBorder";
  if (!C(a.playButtonIcon, b.playButtonIcon)) return "playButtonIcon";
  if (!C(a.previewBg, b.previewBg)) return "previewBg";
  if (!C(a.previewBorder, b.previewBorder)) return "previewBorder";
  if (!C(a.previewTimeBg, b.previewTimeBg)) return "previewTimeBg";
  if (!C(a.previewTimeText, b.previewTimeText)) return "previewTimeText";
  if (!C(a.stageBg, b.stageBg)) return "stageBg";
  if (a.shape.windowRadius != b.shape.windowRadius) return "shape.windowRadius";
  if (a.shape.progressRadius != b.shape.progressRadius) return "shape.progressRadius";
  if (a.shape.knobCircle != b.shape.knobCircle) return "shape.knobCircle";
  if (a.shape.knobSizeOverride != b.shape.knobSizeOverride) return "shape.knobSizeOverride";
  if (a.shape.playButtonCircle != b.shape.playButtonCircle) return "shape.playButtonCircle";
  if (a.shape.playButtonSizeOverride != b.shape.playButtonSizeOverride) return "shape.playButtonSizeOverride";
  if (a.shape.playButtonTinted != b.shape.playButtonTinted) return "shape.playButtonTinted";
  if (a.layout.winW != b.layout.winW) return "layout.winW";
  if (a.layout.winH != b.layout.winH) return "layout.winH";
  if (a.layout.topBarH != b.layout.topBarH) return "layout.topBarH";
  if (a.layout.topBarPadL != b.layout.topBarPadL) return "layout.topBarPadL";
  if (a.layout.botBarH != b.layout.botBarH) return "layout.botBarH";
  if (a.layout.botBarPadX != b.layout.botBarPadX) return "layout.botBarPadX";
  if (a.layout.botBarGap != b.layout.botBarGap) return "layout.botBarGap";
  if (a.layout.btnHit != b.layout.btnHit) return "layout.btnHit";
  if (a.layout.btnBoxW != b.layout.btnBoxW) return "layout.btnBoxW";
  if (a.layout.btnRadius != b.layout.btnRadius) return "layout.btnRadius";
  if (a.layout.btnPitch != b.layout.btnPitch) return "layout.btnPitch";
  if (a.layout.btnIcon != b.layout.btnIcon) return "layout.btnIcon";
  if (a.layout.titleFont != b.layout.titleFont) return "layout.titleFont";
  if (a.layout.badgeFont != b.layout.badgeFont) return "layout.badgeFont";
  if (a.layout.badgeRadius != b.layout.badgeRadius) return "layout.badgeRadius";
  if (a.layout.badgePadX != b.layout.badgePadX) return "layout.badgePadX";
  if (a.layout.badgePadY != b.layout.badgePadY) return "layout.badgePadY";
  if (a.layout.badgeMarginL != b.layout.badgeMarginL) return "layout.badgeMarginL";
  if (a.layout.timeFont != b.layout.timeFont) return "layout.timeFont";
  if (a.layout.winBtnW != b.layout.winBtnW) return "layout.winBtnW";
  if (a.layout.winBtnH != b.layout.winBtnH) return "layout.winBtnH";
  if (a.layout.winIconSize != b.layout.winIconSize) return "layout.winIconSize";
  if (a.layout.winIconStroke != b.layout.winIconStroke) return "layout.winIconStroke";
  if (a.layout.trackH != b.layout.trackH) return "layout.trackH";
  if (a.layout.knobSize != b.layout.knobSize) return "layout.knobSize";
  if (a.layout.knobSizeHover != b.layout.knobSizeHover) return "layout.knobSizeHover";
  if (a.layout.knobHaloDrag != b.layout.knobHaloDrag) return "layout.knobHaloDrag";
  if (a.layout.chapterTickW != b.layout.chapterTickW) return "layout.chapterTickW";
  if (a.layout.chapterTickH != b.layout.chapterTickH) return "layout.chapterTickH";
  if (a.layout.thumbW != b.layout.thumbW) return "layout.thumbW";
  if (a.layout.thumbH != b.layout.thumbH) return "layout.thumbH";
  if (a.layout.thumbRadius != b.layout.thumbRadius) return "layout.thumbRadius";
  if (a.layout.thumbGapAbove != b.layout.thumbGapAbove) return "layout.thumbGapAbove";
  if (a.layout.volW != b.layout.volW) return "layout.volW";
  if (a.layout.volH != b.layout.volH) return "layout.volH";
  if (a.layout.volIcon != b.layout.volIcon) return "layout.volIcon";
  if (a.layout.volKnob != b.layout.volKnob) return "layout.volKnob";
  if (a.layout.volKnobHover != b.layout.volKnobHover) return "layout.volKnobHover";
  if (a.layout.volHitPad != b.layout.volHitPad) return "layout.volHitPad";
  if (a.layout.speedFont != b.layout.speedFont) return "layout.speedFont";
  if (a.layout.speedW != b.layout.speedW) return "layout.speedW";
  if (a.layout.speedItemH != b.layout.speedItemH) return "layout.speedItemH";
  if (a.layout.speedMenuPadY != b.layout.speedMenuPadY) return "layout.speedMenuPadY";
  if (a.layout.btnCircle != b.layout.btnCircle) return "layout.btnCircle";
  if (a.layout.skinBtnSize != b.layout.skinBtnSize) return "layout.skinBtnSize";
  if (a.layout.skinBtnGap != b.layout.skinBtnGap) return "layout.skinBtnGap";
  if (a.layout.skinBtnIcon != b.layout.skinBtnIcon) return "layout.skinBtnIcon";
  if (a.layout.ctxPadX != b.layout.ctxPadX) return "layout.ctxPadX";
  if (a.layout.ctxItemH != b.layout.ctxItemH) return "layout.ctxItemH";
  if (a.layout.ctxRadius != b.layout.ctxRadius) return "layout.ctxRadius";
  if (a.layout.osdIconPad != b.layout.osdIconPad) return "layout.osdIconPad";
  if (a.layout.osdIconR != b.layout.osdIconR) return "layout.osdIconR";
  if (a.layout.osdVolIconR != b.layout.osdVolIconR) return "layout.osdVolIconR";
  if (a.layout.badgeRowGap != b.layout.badgeRowGap) return "layout.badgeRowGap";
  if (a.layout.badgeOriginYWin != b.layout.badgeOriginYWin) return "layout.badgeOriginYWin";
  if (a.layout.titleIconGap != b.layout.titleIconGap) return "layout.titleIconGap";
  if (a.layout.stageCover != b.layout.stageCover) return "layout.stageCover";
  if (a.layout.idleHideSec != b.layout.idleHideSec) return "layout.idleHideSec";
  if (a.layout.fadeSec != b.layout.fadeSec) return "layout.fadeSec";
  if (a.layout.hoverFadeSec != b.layout.hoverFadeSec) return "layout.hoverFadeSec";
  if (a.layout.pressFadeSec != b.layout.pressFadeSec) return "layout.pressFadeSec";
  if (a.layout.btnPressScale != b.layout.btnPressScale) return "layout.btnPressScale";
  if (a.layout.dblClickSec != b.layout.dblClickSec) return "layout.dblClickSec";
  if (a.layout.centerBtnSize != b.layout.centerBtnSize) return "layout.centerBtnSize";
  if (a.layout.centerIconSize != b.layout.centerIconSize) return "layout.centerIconSize";
  if (a.layout.osdRadius != b.layout.osdRadius) return "layout.osdRadius";
  if (a.layout.osdEdgeGap != b.layout.osdEdgeGap) return "layout.osdEdgeGap";
  if (a.layout.osdTopGap != b.layout.osdTopGap) return "layout.osdTopGap";
  if (a.layout.osdVolW != b.layout.osdVolW) return "layout.osdVolW";
  if (a.layout.osdVolH != b.layout.osdVolH) return "layout.osdVolH";
  if (a.layout.osdBarThick != b.layout.osdBarThick) return "layout.osdBarThick";
  if (a.layout.osdBarLen != b.layout.osdBarLen) return "layout.osdBarLen";
  if (a.layout.osdSeekH != b.layout.osdSeekH) return "layout.osdSeekH";
  if (a.layout.osdMaxHRatio != b.layout.osdMaxHRatio) return "layout.osdMaxHRatio";
  if (a.layout.osdFont != b.layout.osdFont) return "layout.osdFont";
  if (a.layout.miniLineH != b.layout.miniLineH) return "layout.miniLineH";
  if (a.layout.miniLineMaxAlpha != b.layout.miniLineMaxAlpha) return "layout.miniLineMaxAlpha";
  if (a.layout.osdFadeIn != b.layout.osdFadeIn) return "layout.osdFadeIn";
  if (a.layout.osdHold != b.layout.osdHold) return "layout.osdHold";
  if (a.layout.osdFadeOut != b.layout.osdFadeOut) return "layout.osdFadeOut";
  if (a.layout.promptFont != b.layout.promptFont) return "layout.promptFont";
  if (a.layout.promptBarH != b.layout.promptBarH) return "layout.promptBarH";
  if (a.layout.promptBtnW != b.layout.promptBtnW) return "layout.promptBtnW";
  if (a.layout.promptBtnH != b.layout.promptBtnH) return "layout.promptBtnH";
  if (a.layout.promptBarRadius != b.layout.promptBarRadius) return "layout.promptBarRadius";
  if (a.layout.promptBtnRadius != b.layout.promptBtnRadius) return "layout.promptBtnRadius";
  if (a.layout.promptPad != b.layout.promptPad) return "layout.promptPad";
  if (a.layout.promptGap != b.layout.promptGap) return "layout.promptGap";
  if (a.layout.promptMaxW != b.layout.promptMaxW) return "layout.promptMaxW";
  if (a.layout.promptHoldSec != b.layout.promptHoldSec) return "layout.promptHoldSec";
  if (a.layout.promptFadeSec != b.layout.promptFadeSec) return "layout.promptFadeSec";
  return nullptr;
}
}  // namespace fr
